name: CI - PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
    CARGO_TERM_COLOR: always

jobs:
  clippy-fmt-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run clippy
        run: cargo clippy

      - name: Run tests
        run: cargo nextest run
